name: energise_test
description: "Test application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  animations: ^2.0.11
  avatar_glow: ^3.0.1

  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/flags/
